buku1 = 25000
uang = 200000
buku = 25000 * 3
pulpen = 8000 * 2
flashdisk = 75000
total = buku + pulpen + flashdisk
diskon = float(total * 10) / 100
setelahDiskon = total - diskon
pajak = float(setelahDiskon * 11) / 100
totalBayar = setelahDiskon + pajak
kembalian = uang - totalBayar
bukuDanFlashdisk = buku1 + flashdisk
print("total harga buku = Rp" + str(buku))
print("total harga pulpen = Rp" + str(pulpen))
print("total harga flashdisk = Rp" + str(flashdisk))
print("total seluruh barang = Rp" + str(total))
print("diskon yang didapatkan = Rp" + str(diskon))
print("harga setelah diskon = Rp" + str(setelahDiskon))
print("pajak yang harus dibayarkan = Rp" + str(pajak))
print("total yang harus dibayarkan = Rp" + str(totalBayar))
print("uang kembalian yang didapatkan = Rp" + str(kembalian))
print("total harga buku dan flashdisk = Rp." + str(bukuDanFlashdisk))
