uang = 200000
buku = 3 * 25000
pulpen = 2 * 8000
flashdisk = 1 * 75000
total = buku + pulpen + flashdisk
diskon = float(total * 10) / 100
setelahDiskon = total - diskon
pajak = float(setelahDiskon * 11) / 100
totalBayar = setelahDiskon + pajak
kembalian = uang - totalBayar
print("Total harga buku = Rp" + str(buku))
print("Total harga pulpen = Rp" + str(pulpen))
print("Total harga flashdisk = Rp" + str(flashdisk))
print("Total seluruh barang = Rp" + str(total))
print("diskon yang didapat = Rp" + str(diskon))
print("Harga Setelah Diskon = Rp" + str(setelahDiskon))
print("pajak yang harus dibayar = Rp" + str(pajak))
print("Total yang harus dibayar = Rp" + str(totalBayar))
print("uang kembalian = Rp" + str(kembalian))
