uang = 200000
jumlahbuku = 3
hargabuku = 25000
jumlahbolpoin = 2
hargabolpoin = 8000
jumlahflashdisk = 1
hargaflashdisk = 75000
totalbuku = jumlahbuku * hargabuku
totalbolpoin = jumlahbolpoin * hargabolpoin
totalflashdisk = jumlahflashdisk * hargaflashdisk
totalbelanja = totalbuku + totalbolpoin + totalflashdisk
diskon = totalbelanja * 0.1
setelahdiskon = totalbelanja - diskon
pajak = setelahdiskon * 0.11
totalbayar = setelahdiskon + pajak
kembalian = uang - totalbayar
print("1. total harga buku = Rp." + str(totalbuku))
print("2. total harga bolpoin= Rp." + str(totalbolpoin))
print("3. total harga flashdisk = Rp." + str(totalflashdisk))
print("4. total belanja = Rp." + str(totalbelanja))
print("5. diskon = Rp." + str(diskon))
print("6. total sebelum diskon = Rp." + str(totalbelanja))
print("7. total setelah diskon = Rp." + str(setelahdiskon))
print("8. terkena pajak 11% = Rp." + str(pajak))
print("9. total pembayaran = Rp." + str(totalbayar))
