uang = 200000
totalhargabuku = 75000
totalhargapulpen = 8000
totalhargaflashdisk = 75000
totalsebelumdiskon = 166000
diskon = 0.1
hargasetelahdiskon = 149400
pPN = 0.11
totalpembayaran = 165834
uangkembalian = 34166
print("a) Total harga buku = " + str(totalhargabuku))
print("b) Total harga pulpen = " + str(totalhargapulpen))
print("c) Total harga flashdisk = " + str(totalhargaflashdisk))
print("d) Total sebelum diskon = " + str(totalsebelumdiskon))
print("e) diskon 10% = " + str(diskon))
print("f) Harga setelah diskon = " + str(hargasetelahdiskon))
print("g) Pajak = " + str(pPN))
print("h) Total pembayaran = " + str(totalpembayaran))
print("i) Kembalian = " + str(uangkembalian))
